goal_phase_controller_client:
  ros__parameters:
    frame_id: "map"
    goals.001: [5.7, 8.75, 0.7]
    goals.002: [5.7, 8.75, 1.57]
    goals.003: [5.67, 9.6, 1.57]
    goals.004: [5.67, 9.6, 1.57]
    # x, y, yaw 값을 원하는 만큼 추가