<?xml version="1.0"?>
<robot name="rHomMover_1"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Colors -->
    <material name="black">
      <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <material name="dark">
        <color rgba="0.3 0.3 0.3 1.0"/>
    </material>

    <material name="light_black">
        <color rgba="0.4 0.4 0.4 1.0"/>
    </material>

    <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
    </material>

    <material name="green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
    </material>

    <material name="orange">
        <color rgba="1.0 0.4235 0.0392 1.0"/>
    </material>

    <material name="brown">
        <color rgba="0.8706 0.8118 0.7647 1.0"/>
    </material>

    <material name="red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>

    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <!-- 주요 기하 변수 -->
    <xacro:property name ="W_B" value="1.0"/>
    <xacro:property name ="L_B" value="1.0"/>
    <xacro:property name ="T_B" value="0.1"/>
    <xacro:property name ="L_a" value="0.3"/>
    <xacro:property name ="D_a" value="0.1"/>
    <xacro:property name ="W_w" value="0.09"/>
    <xacro:property name ="D_w" value="0.4"/>
    <xacro:property name ="H" value="${D_w /2}"/>

    <!-- BASE -->
    <!-- 이거 왜 이렇게 분리하는지는 모르겠는데 일단 참고 사이트에서 이케 하길래 따라함 -->
    <link name="base_link">
    </link>

    <!-- BODY LINK -->
    <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body"/>
    </joint>

    <link name="body">
        <visual>
            <origin xyz="-${L_B/2} 0 ${H}"/>
            <geometry>
                <box size="${L_B} ${W_B} ${T_B}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="-${L_B/2} 0 ${H}"/>
            <geometry>
                <box size="${L_B} ${W_B} ${T_B}"/>
            </geometry>
        </collision>
    </link>

    <!-- 오른쪽 팔+바퀴 -->
    <joint name="right_arm_joint" type="continuous">
        <parent link="body"/>
        <child link="right_arm"/>
        <origin xyz="0 -${W_B/2} ${D_w/2}"/>
        <axis xyz = "0 0 1"/>
    </joint>

    <link name="right_arm">
        <visual>
            <origin xyz = "0 -${L_a/2} 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_a/2}" length="${L_a}"/>
            </geometry>
            <material name="orange"/>
        </visual>
    </link>


    <joint name="right_wheel_joint" type="continuous">
        <parent link ="right_arm"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${L_a} 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_w/2}" length="${W_w}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_w/2}" length="${W_w}"/>
            </geometry>
        </collision>
    </link>

    <!-- 왼쪽 팔+바퀴 -->
    <joint name="left_arm_joint" type="continuous">
        <parent link="body"/>
        <child link="left_arm"/>
        <origin xyz="0 ${W_B/2} ${D_w/2}"/>
        <axis xyz = "0 0 -1"/>
    </joint>

    <link name="left_arm">
        <visual>
            <origin xyz = "0 ${L_a/2} 0" rpy="-${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_a/2}" length="${L_a}"/>
            </geometry>
            <material name="orange"/>
        </visual>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <parent link ="left_arm"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${L_a} 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="-${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_w/2}" length="${W_w}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="-${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_w/2}" length="${W_w}"/>
            </geometry>
        </collision>
    </link>

    <!-- 뒤쪽 받침대 -->
    <joint name="tail_joint" type="fixed">
        <parent link="body"/>
        <child link="tail"/>
        <origin xyz="-${L_B} 0 ${D_w/2}"/>
    </joint>

    <link name="tail">
        <visual>
            <origin xyz = "0 0 -${H/2-D_a/4}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${D_a/2}" length="${H-D_a/2}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz = "0 0 -${H/2-D_a/4}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${D_a/2}" length="${H-D_a/2}"/>
            </geometry>
        </collision>
    </link>

    <joint name="tail_caster_joint" type="fixed">
        <parent link ="tail"/>
        <child link="caster"/>
        <origin xyz="0 0 -${H-D_a/4}"/>
    </joint>

    <link name="caster">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${D_a/2}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${D_a/2}"/>
            </geometry>
        </collision>
    </link>


</robot>