<?xml version="1.0"?>
<!--일단 어깨 관절을 고정시키고, diff driver를 사용해서 잘 되는지 확인 완료-->
<robot name="rHomMover_4"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Macro -->
    <xacro:include filename="macros.xacro"/>

    <!-- Colors -->
    <material name="black">
      <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <material name="dark">
        <color rgba="0.3 0.3 0.3 1.0"/>
    </material>

    <material name="light_black">
        <color rgba="0.4 0.4 0.4 1.0"/>
    </material>

    <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
    </material>

    <material name="green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
    </material>

    <material name="orange">
        <color rgba="1.0 0.4235 0.0392 1.0"/>
    </material>

    <material name="brown">
        <color rgba="0.8706 0.8118 0.7647 1.0"/>
    </material>

    <material name="red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>

    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <!-- 주요 기하 변수 -->
    <xacro:property name ="W_B" value="0.5"/>
    <xacro:property name ="L_B" value="0.5"/>
    <xacro:property name ="T_B" value="0.05"/>
    <xacro:property name ="L_a" value="0.15"/>
    <xacro:property name ="D_a" value="0.05"/>
    <xacro:property name ="W_w" value="0.045"/>
    <xacro:property name ="D_w" value="0.2"/>
    <xacro:property name ="H" value="${D_w /2}"/>

    <!-- BASE -->
    <!-- 이거 왜 이렇게 분리하는지는 모르겠는데 일단 참고 사이트에서 이케 하길래 따라함 -->
    <link name="base_link">
    </link>

    <!-- BODY LINK -->
    <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body"/>
    </joint>

    <link name="body">
        <visual>
            <origin xyz="-${L_B/2} 0 ${H}"/>
            <geometry>
                <box size="${L_B} ${W_B} ${T_B}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="-${L_B/2} 0 ${H}"/>
            <geometry>
                <box size="${L_B} ${W_B} ${T_B}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x = "${L_B}" y= "${W_B}" z="${T_B}">
            <origin xyz="-${L_B/2} 0 ${H}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="body">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- 오른쪽 팔+바퀴 fixed 버전 -->
    <joint name="right_arm_joint" type="fixed">
        <parent link="body"/>
        <child link="right_arm"/>
        <origin xyz="0 -${W_B/2} ${D_w/2}"/>
    </joint>


    <!-- 오른쪽 팔+바퀴 R 조인트 버전 -->
    <!-- <joint name="right_arm_joint" type="continuous">
        <parent link="body"/>
        <child link="right_arm"/>
        <origin xyz="0 -${W_B/2} ${D_w/2}"/>
        <axis xyz = "0 0 1"/>
    </joint> -->

    <link name="right_arm">
        <visual>
            <origin xyz = "0 -${L_a/2} 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_a/2}" length="${L_a}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <xacro:inertial_cylinder mass="0.1" radius="${D_a/2}" length="${L_a}">
            <origin xyz = "0 -${L_a/2} 0" rpy="${pi/2} 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="right_arm">
        <material>Gazebo/Black</material>
    </gazebo>


    <joint name="right_wheel_joint" type="continuous">
        <parent link ="right_arm"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${L_a} 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_w/2}" length="${W_w}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_w/2}" length="${W_w}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" radius="${D_w/2}" length="${W_w}">
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!--오른쪽바퀴에 마찰력 적용-->
    <gazebo reference="right_wheel">
        <mu1>1.5</mu1>
        <mu2>0.8</mu2>
    </gazebo>

    <!-- 왼쪽 팔+바퀴 fixed 버전, 나중에 바꿔줘야 함.  -->
    <joint name="left_arm_joint" type="fixed">
        <parent link="body"/>
        <child link="left_arm"/>
        <origin xyz="0 ${W_B/2} ${D_w/2}"/>
    </joint>
    <!-- 왼쪽 팔+바퀴 R 조인트-->
    <!-- <joint name="left_arm_joint" type="continuous">
        <parent link="body"/>
        <child link="left_arm"/>
        <origin xyz="0 ${W_B/2} ${D_w/2}"/>
        <axis xyz = "0 0 -1"/>
    </joint> -->

    <link name="left_arm">
        <visual>
            <origin xyz = "0 ${L_a/2} 0" rpy="-${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_a/2}" length="${L_a}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <xacro:inertial_cylinder mass="0.1" radius="${D_a/2}" length="${L_a}">
            <origin xyz = "0 ${L_a/2} 0" rpy="-${pi/2} 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="left_arm">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="left_wheel_joint" type="continuous">
        <parent link ="left_arm"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${L_a} 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="-${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_w/2}" length="${W_w}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="-${pi/2} 0 0"/>
            <geometry>
                <cylinder radius="${D_w/2}" length="${W_w}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" radius="${D_w/2}" length="${W_w}">
            <origin xyz="0 0 0" rpy="-${pi/2} 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!--왼쪽바퀴에 마찰력 적용-->
    <gazebo reference="left_wheel">
        <mu1>1.5</mu1>
        <mu2>0.8</mu2>
    </gazebo>

    <!-- 뒤쪽 받침대 -->
    <joint name="tail_joint" type="fixed">
        <parent link="body"/>
        <child link="tail"/>
        <origin xyz="-${L_B} 0 ${D_w/2}"/>
    </joint>

    <link name="tail">
        <visual>
            <origin xyz = "0 0 -${H/2-D_a/4}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${D_a/2}" length="${H-D_a/2}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz = "0 0 -${H/2-D_a/4}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${D_a/2}" length="${H-D_a/2}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" radius="${D_a/2}" length="${H-D_a/2}">
            <origin xyz = "0 0 -${H/2-D_a/4}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="tail">
        <material>Gazebo/Black</material>
    </gazebo>
    

    <joint name="tail_caster_joint" type="fixed">
        <parent link ="tail"/>
        <child link="caster"/>
        <origin xyz="0 0 -${H-D_a/4}"/>
    </joint>

    <link name="caster">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${D_a/2}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${D_a/2}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.05" radius="${D_a/2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <!--캐스터휠에 마찰력 적용-->
    <gazebo reference="caster">
        <mu1>0.01</mu1>
        <mu2>0.01</mu2>
    </gazebo>

    <xacro:include filename="gazebo.xacro"/>
    




</robot> 
